name: Update list every 10 min

on:
  #schedule:
    #- cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download and build lists
        run: |
          # Только CAT
          curl -s https://raw.githubusercontent.com/ShadowException/VPN/refs/heads/main/configs/VPN-cat-top-50 \
          | tail -n +9 > cat.txt

          #только mera
          #MeraVPN
          curl -s https://raw.githubusercontent.com/meraws/MeraServers/refs/heads/inside/sub \
          | tail -n +7 >> mera.txt
          
          # Создаём all.txt (очищаем)
          > all.txt

          # CAT
          curl -s https://raw.githubusercontent.com/ShadowException/VPN/refs/heads/main/configs/VPN-cat-top-50 \
          | tail -n +9 >> all.txt

          # IGARECK
          curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt \
          | tail -n +6 >> all.txt

          
          # # IGARECK
          # curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt \
          # | tail -n +6 >> all.txt

          
          curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt \
          | tail -n +6 >> all.txt

          #ZIENG
          #curl -s https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt >> all.txt

          
          #ZIENG
          curl -s https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt >> all.txt

          ##MeraVPN
          #curl -s https://raw.githubusercontent.com/meraws/MeraServers/refs/heads/inside/sub \
          #| tail -n +7 >> all.txt
          
          # Удаляем дубликаты
          sort -u all.txt -o all.txt

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add cat.txt all.txt mera.txt
          git diff --cached --quiet || git commit -m "Auto update list"
          git push
