name: Update list every 10 min

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download and trim list
        run: |
          curl -s https://raw.githubusercontent.com/VPN-cat/VPN/refs/heads/main/configs/VPN-cat-top-50 \
          | tail -n +9 > output.txt

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.txt
          git diff --cached --quiet || git commit -m "Auto update list"
          git push
